name: 'Super-Jetpack'
author: 'ThatJavaGuy'
version: '1.8'
main: com.cainkilgore.jetpack.Jetpack
commands:
   jetpack:
       description: 'Gives you an item of the Super Jetpack plugin'
       usage: /<command> [give/checkforupdates/list/toggleparticles/togglescoreboard] <item>